// <auto-generated />
using System;
using AndBank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AndBank.Infrastructure.Migrations
{
    [DbContext(typeof(AndBankDbContext))]
    [Migration("20251102203337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AndBank.Domain.Entities.Position", b =>
                {
                    b.Property<string>("PositionId")
                        .HasColumnType("text")
                        .HasColumnName("position_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("PositionId", "Date");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_positions_client");

                    b.HasIndex("Value")
                        .HasDatabaseName("idx_positions_value");

                    b.HasIndex("PositionId", "Date")
                        .HasDatabaseName("idx_positions_positionid_date");

                    b.ToTable("positions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
